spring.datasource.url=jdbc:postgresql://${himanshu.database.writerendpoint}:${himanshu.database.port}/${himanshu.database.name}
spring.datasource.username=postgres
spring.datasource.password=postgres

himanshu.database.writerendpoint=studentdevdb.ckpdyguv9yre.us-west-2.rds.amazonaws.com
himanshu.database.port=5432
himanshu.database.name=studentDevDb